### PR TITLE
Registration bug fix & hotel reducers & actions

### LINKED ISSUE #34: Registration fix

### PR DESCRIPTION
**Pull request by DianaIgnatescu**
# Description

This PR should now set the correct values for the current user.
I also added actions and hotel reducers. 

Fixes #34 )

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

- [ ] This change requires a documentation update

## Change status

- [ ] Complete, tested, ready to review and merge

- [x] Complete, but not tested (may need new tests)

- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

Tested locally.

# Checklist:

- [x] My code follows the style guidelines of this project

- [x] I have performed a self-review of my own code

- [ ] I have commented my code, particularly in hard-to-understand areas

- [ ] I have made corresponding changes to the documentation, if relevant

- [x] I have run the app using my feature and ensured that no functionality is broken

- [x] My changes generate no new warnings

- [ ] There are no merge conflicts

### CODE REVIEW

File: src/store/reducers/currentUser.js [hunk 1]
```diff
@@ -12,7 +12,8 @@ const currentUser = (state = initialState, action) => {
         token: action.payload.token,
         user_type: action.payload.user_type,
         name: action.payload.name,
-
+        hotel_name: action.payload.hotel_name,
```
Comment (mark-marshall) [inline src/store/reducers/currentUser.js]: Not sure if you've changed this already, but in this file, we also need to set '_id: action.payload.id,' instead of '_id: action.payload._id'

Comment (DianaIgnatescu) [reply src/store/reducers/currentUser.js]: Should be good now. I removed the _

Comment (mark-marshall) [reply src/store/reducers/currentUser.js]: Awesome, one more, can we add the motto onto currentUser?

File: src/views/CompanySettings.js [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+
+import SuperAdminNav from '../components/SuperAdminNav';
+
+class CompanySettings extends React.Component {
+  constructor(props) {
+    super(props);
+
+    this.props = props;
+    const { state, dispatchFetchSingleHotel } = this.props;
+    this.state = { companyName: state.hotel.name, companyMotto: state.hotel.motto };
```
Comment (Pav0l) [inline src/views/CompanySettings.js]: This should be on global state store. And from there connected to this component in `mapStateToProps`

File: src/views/CompanySettings.js [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+  };
+}
+
+CompanySettings.propTypes = {
+  state: PropTypes.shape().isRequired,
+  dispatchFetchSingleHotel: PropTypes.func.isRequired,
+  dispatchUpdateHotel: PropTypes.func.isRequired,
+};
+
+const mapStateToProps = state => ({ state });
```
Comment (Pav0l) [inline src/views/CompanySettings.js]: This should not access the whole `state` tree. It's very bad for apps performance, as it will rerender this component on any state change anywhere in the app. See more here https://react-redux.js.org/api/connect#example-usage

Only map that part of state to props, that this component needs (hotel info in this case)

File: src/store/reducers/currentUser.js (hunk 1 above)
Comment (DianaIgnatescu) [reply src/store/reducers/currentUser.js]: Updated to include motto

File: src/index.js [hunk 4]
```diff
@@ -21,7 +21,7 @@ const store = createStore(
 
 const currentUser = JSON.parse(localStorage.getItem('currentUser'));
 if (currentUser) {
-  store.dispatch(loginSuccess(currentUser.id, currentUser.hotel_id, currentUser.email, currentUser.name, currentUser.user_type, currentUser.token));
+  store.dispatch(loginSuccess(currentUser.id, currentUser.hotel_id, currentUser.email, currentUser.token, currentUser.user_type, currentUser.name));
```
[the remark this answers is not in the document]
Comment (DianaIgnatescu) [reply src/index.js]: This should work fine now

File: src/views/CompanySettings.js (hunk 3 above)
Comment (DianaIgnatescu) [reply src/views/CompanySettings.js]: I made the required changes now

File: src/views/Register.js [hunk 5]
```diff
@@ -82,7 +82,7 @@ const Register = ({ loggedIn, registerUser }) => {
         <label>Hotel Motto</label>
         <input name="hotelMotto" placeholder="Your hotel motto..." type="text" />
         <p id="result-message" />
-        <button type="submit" onClick={(e) => handleRegister(e, registerUser)}>Register</button>
+        <button type="submit" onClick={(e) => {debugger; handleRegister(e, registerUser)}}>Register</button>
```
[the remark this answers is not in the document]
Comment (DianaIgnatescu) [reply src/views/Register.js]: Removed the debugger

File: src/store/actions/auth.js [hunk 6]
```diff
@@ -37,9 +37,9 @@ export const logout = () => ({
   type: LOGOUT,
 });
 
-export const loginSuccess = (id, hotel_id, email, token, user_type, name) => {
+export const loginSuccess = (id, hotel_id, email, token, user_type, name, motto) => {
   const currentUser = {
-    id, hotel_id, email, token, user_type, name,
+    id, hotel_id, email, token, user_type, name, motto
   };
```
Comment (Pav0l) [inline src/store/actions/auth.js]: The whole `currentUser` could have been the argument for the `loginSuccess` function :)

File: src/views/Register.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (Pav0l) [reply src/views/Register.js]: 👀

File: src/index.js [hunk 7]
```diff
@@ -21,7 +21,7 @@ const store = createStore(
 
 const currentUser = JSON.parse(localStorage.getItem('currentUser'));
 if (currentUser) {
-  store.dispatch(loginSuccess(currentUser.id, currentUser.hotel_id, currentUser.email, currentUser.name, currentUser.user_type, currentUser.token));
+  store.dispatch(loginSuccess(currentUser.id, currentUser.hotel_id, currentUser.email, currentUser.token, currentUser.user_type, currentUser.name, currentUser.motto));
```
Comment (Pav0l) [inline src/index.js]: Why not pass in the whole `currentUser` object?

File: src/views/CompanySettings.js [hunk 8]
```diff
@@ -0,0 +1,89 @@
...
+
+const mapStateToProps = state => ({
+  hotel: state.hotel,
+  currentUser: state.currentUser,
+});
+
+export default connect(mapStateToProps, {
+  dispatchFetchSingleHotel: fetchSingleHotel,
+  dispatchUpdateHotel: updateHotel,
+})(CompanySettings);
```
Comment (Pav0l) [inline src/views/CompanySettings.js]: nice! 🚀
